// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargotest

import (
	"context"
	"net/http"
	"slices"

	"github.com/amritk/scalar-go/internal/apijson"
	"github.com/amritk/scalar-go/internal/requestconfig"
	"github.com/amritk/scalar-go/option"
)

// PingService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPingService] method instead.
type PingService struct {
	Options []option.RequestOption
}

// NewPingService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPingService(opts ...option.RequestOption) (r *PingService) {
	r = &PingService{}
	r.Options = opts
	return
}

// Ping the API
//
// Parameters:
//
//	ctx: Context for the request.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PingPingResponse: pong
//
// Example:
//
//	ping, err := client.Ping.Ping(context.Background())
//	if err != nil {
//		panic(err)
//	}
//	fmt.Println(ping)
func (r *PingService) Ping(ctx context.Context, opts ...option.RequestOption) (res *PingPingResponse, err error) {
	opts = slices.Concat(r.Options, opts)
	path := "ping"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PingPingResponse struct {
	Message string               `json:"message"`
	JSON    pingPingResponseJSON `json:"-"`
}

// pingPingResponseJSON contains the JSON metadata for the struct [PingPingResponse]
type pingPingResponseJSON struct {
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PingPingResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r pingPingResponseJSON) RawJSON() string {
	return r.raw
}
