// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalar

import (
	"github.com/amritk/scalar-go/option"
)

// PlanetService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPlanetService] method instead.
type PlanetService struct {
	Options []option.RequestOption
	Pizzas  *PlanetPizzaService
}

// NewPlanetService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPlanetService(opts ...option.RequestOption) (r *PlanetService) {
	r = &PlanetService{}
	r.Options = opts
	r.Pizzas = NewPlanetPizzaService(opts...)
	return
}
