// Code generated by Scalar SDK Generator. DO NOT EDIT.

package scalargalaxy

import (
	"errors"
	"net/http"
	"slices"

	standardwebhooks "github.com/standard-webhooks/standard-webhooks/libraries/go"

	"github.com/amritk/scalar-go/internal/apijson"
	"github.com/amritk/scalar-go/internal/requestconfig"
	"github.com/amritk/scalar-go/option"
)

// WebhookService contains methods that help with parsing and verifying inbound
// webhook payloads. You should not instantiate this service directly, and
// instead use the [NewWebhookService] method instead.
type WebhookService struct {
	Options []option.RequestOption
}

// NewWebhookService generates a new service that applies the given options to each
// request. These options are applied after the parent client's options (if there
// is one), and before any request-specific options.
func NewWebhookService(opts ...option.RequestOption) (r *WebhookService) {
	r = &WebhookService{}
	r.Options = opts
	return
}

// Parsed verifies the webhook signature using the WebhookSecret option (set on the
// client or per call) and decodes the payload into a [ParsedWebhookEvent].
func (r *WebhookService) Parsed(payload []byte, headers http.Header, opts ...option.RequestOption) (*ParsedWebhookEvent, error) {
	opts = slices.Concat(r.Options, opts)
	cfg, err := requestconfig.PreRequestOptions(opts...)
	if err != nil {
		return nil, err
	}
	key := cfg.WebhookSecret
	if key == "" {
		return nil, errors.New("The WebhookSecret option must be set in order to verify webhook headers")
	}
	wh, err := standardwebhooks.NewWebhook(key)
	if err != nil {
		return nil, err
	}
	err = wh.Verify(payload, headers)
	if err != nil {
		return nil, err
	}
	res := &ParsedWebhookEvent{}
	err = res.UnmarshalJSON(payload)
	if err != nil {
		return res, err
	}
	return res, nil
}

type ParsedWebhookEvent struct {
	JSON parsedWebhookEventJSON `json:"-"`
}

type parsedWebhookEventJSON struct {
	ExtraFields map[string]apijson.Field
	raw         string
}

func (r *ParsedWebhookEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r parsedWebhookEventJSON) RawJSON() string {
	return r.raw
}
